import { IPaises } from "./paises.model";

// export const paises: IPaises[] = [
//     { 'nome': 'Antígua e Barbuda', 'img': 'assets/img/antigua-and-barbuda.png', 'descrisao': 'Antígua e Barbuda é um país do caribe sua capital é Saint John e seu idioma oficial é o inglês.' },
//     { 'nome': 'Argentina', 'img': 'assets/img/argentina.png', 'descrisao': 'Argentina é um país da américa do sul sua capital é Buenos Aires e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Aruba', 'img': 'assets/img/aruba.png', 'descrisao': 'Aruba é um país do caribe sua capital é Oranjestad e seus idiomas oficiais são holandês e papiamento.' },
//     { 'nome': 'Bahamas', 'img': 'assets/img/bahamas.png', 'descrisao': 'Bahamas é um país do caribe sua capital é Nassau e seu idioma oficial é o inglês.' },
//     { 'nome': 'Barbados', 'img': 'assets/img/barbados.png', 'descrisao': 'Barbados é um país do caribe sua capital é Bridgetown e seu idioma oficial é o inglês.' },
//     { 'nome': 'Belize', 'img': 'assets/img/belize.png', 'descrisao': 'Belize é um país da américa central sua capital é Belmopan e seu idioma oficial é o inglês.' },
//     { 'nome': 'Bolívia', 'img': 'assets/img/bolivia.png', 'descrisao': 'Bolívia é um país da américa do sul sua capital é La Paz e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Brasil', 'img': 'assets/img/brazil.png', 'descrisao': 'Brasil é um país da américa do sul sua capital é Brasília e seu idioma oficial é o português.' },
//     { 'nome': 'Canadá', 'img': 'assets/img/canada.png', 'descrisao': 'Canadá é um país da américa do norte sua capital é Ottawa e seus idiomas oficiais são o inglês e francês.' },
//     { 'nome': 'Chile', 'img': 'assets/img/chile.png', 'descrisao': 'Chile é um país da américa do sul sua capital é Santiago e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Colômbia', 'img': 'assets/img/colombia.png', 'descrisao': 'Colômbia é um país da américa do sul sua capital é Bogotá e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Costa Rica', 'img': 'assets/img/costa-rica.png', 'descrisao': 'Costa Rica é um país da américa central sua capital é San José e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Costa Rica', 'img': 'assets/img/costa-rica.png', 'descrisao': 'Costa Rica é um país da américa central sua capital é San José e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Costa Rica', 'img': 'assets/img/costa-rica.png', 'descrisao': 'Costa Rica é um país da américa central sua capital é San José e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Costa Rica', 'img': 'assets/img/costa-rica.png', 'descrisao': 'Costa Rica é um país da américa central sua capital é San José e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Costa Rica', 'img': 'assets/img/costa-rica.png', 'descrisao': 'Costa Rica é um país da américa central sua capital é San José e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Costa Rica', 'img': 'assets/img/costa-rica.png', 'descrisao': 'Costa Rica é um país da américa central sua capital é San José e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Costa Rica', 'img': 'assets/img/costa-rica.png', 'descrisao': 'Costa Rica é um país da américa central sua capital é San José e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Costa Rica', 'img': 'assets/img/costa-rica.png', 'descrisao': 'Costa Rica é um país da américa central sua capital é San José e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Costa Rica', 'img': 'assets/img/costa-rica.png', 'descrisao': 'Costa Rica é um país da américa central sua capital é San José e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Costa Rica', 'img': 'assets/img/costa-rica.png', 'descrisao': 'Costa Rica é um país da américa central sua capital é San José e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Costa Rica', 'img': 'assets/img/costa-rica.png', 'descrisao': 'Costa Rica é um país da américa central sua capital é San José e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Costa Rica', 'img': 'assets/img/costa-rica.png', 'descrisao': 'Costa Rica é um país da américa central sua capital é San José e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Costa Rica', 'img': 'assets/img/costa-rica.png', 'descrisao': 'Costa Rica é um país da américa central sua capital é San José e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Costa Rica', 'img': 'assets/img/costa-rica.png', 'descrisao': 'Costa Rica é um país da américa central sua capital é San José e seu idioma oficial é o espanhol.' },
//     { 'nome': 'Costa Rica', 'img': 'assets/img/costa-rica.png', 'descrisao': 'Costa Rica é um país da américa central sua capital é San José e seu idioma oficial é o espanhol.' }
// ]